### ISSUE TITLE
game crash while braking leaves

### ISSUE THREAD

**Issue by mando222** [mando222/NomadsRPG#53]

**Comment by mando222** [comment]
```20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: java.lang.ClassNotFoundException: toughasnails.season.SeasonASMHelper
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at java.lang.Class.forName0(Native Method)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at java.lang.Class.forName(Class.java:260)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at CoroUtil.util.CoroUtilCompatibility.isTANInstalled(CoroUtilCompatibility.java:57)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at CoroUtil.util.CoroUtilCompatibility.getAdjustedTemperature(CoroUtilCompatibility.java:33)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at weather2.client.SceneEnhancer.tickParticlePrecipitation(SceneEnhancer.java:514)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at weather2.client.SceneEnhancer.tickClient(SceneEnhancer.java:156)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at weather2.ClientTickHandler.onTickInGame(ClientTickHandler.java:110)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at weather2.EventHandlerFML.tickClient(EventHandlerFML.java:40)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_755_EventHandlerFML_tickClient_ClientTickEvent.invoke(.dynamic)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:51:30] [main/INFO]: [CoroUtil.util.CoroUtilCompatibility:isTANInstalled:62]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:51:30] [main/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[20:51:36] [Server thread/INFO]: Saving chunks for level 'test2'/the_nether
[20:51:36] [Server thread/INFO]: Saving chunks for level 'test2'/the_end
[20:51:36] [Server thread/INFO]: Saving chunks for level 'test2'/Betweenlands
[20:51:36] [Server thread/INFO]: Saving chunks for level 'test2'/twilight_forest
[20:51:39] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 13589ms behind, skipping 271 tick(s)
[20:51:39] [main/INFO]: Loaded 718 advancements
[20:51:43] [Server thread/INFO]: Saving and pausing game...
[20:51:43] [Server thread/INFO]: Saving chunks for level 'test2'/overworld
[20:51:43] [Server thread/INFO]: Saving chunks for level 'test2'/the_nether
[20:51:43] [Server thread/INFO]: Saving chunks for level 'test2'/the_end
[20:51:43] [Server thread/INFO]: Saving chunks for level 'test2'/Betweenlands
[20:51:43] [Server thread/INFO]: Saving chunks for level 'test2'/twilight_forest
[20:52:11] [Server thread/INFO]: [mando222: Set own game mode to Survival Mode]
[20:52:11] [main/INFO]: [CHAT] Your game mode has been updated to Survival Mode
[20:52:26] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=camping:hemp, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[awu$a.class:?]
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:139) ~[BlockBOPGrass.class:?]
	at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:75) ~[Hemp.class:?]
	at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56) ~[Hemp.class:?]
	at net.minecraft.block.Block.func_180645_a(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more
[20:52:27] [Server thread/ERROR]: This crash report has been saved to: C:\Users\mando222\Documents\Curse\Minecraft\Instances\Nomads\crash-reports\crash-2018-02-05_20.52.26-server.txt
[20:52:27] [Server thread/INFO]: Stopping server
[20:52:27] [Server thread/INFO]: Saving players
[20:52:27] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  SHLoadingPlugin (ScalingHealth-1.12-1.3.9-89.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/5/18 8:52 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=camping:hemp, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:139)
	at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:75)
	at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:139)
	at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:75)
	at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: test2
	All players: 1 total; [EntityPlayerMP['mando222'/1214, l='test2', x=471.30, y=66.00, z=454.02]]
	Chunk stats: ServerChunkCache: 904 Drop: 0
	Level seed: 2687708205730118042
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (455,64,357), Chunk: (at 7,4,5 in 28,22; contains blocks 448,0,352 to 463,255,367), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 825 game time, 825 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 126523 (now: false), thunder time: 176129 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 820216304 bytes (782 MB) / 2850553856 bytes (2718 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 Optifine OptiFine_1.12.2_HD_U_C8 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                  | Source                                             | Signature                                |
	|:--------- |:------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                   | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                     | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                | forge-1.12.2-14.23.2.2611.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.2.2611             | forge-1.12.2-14.23.2.2611.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit           | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | akashictome         | 1.2-10                   | AkashicTome-1.2-10.jar                             | None                                     |
	| UCHIJAAAA | biomesoplenty       | 7.0.1.2302               | BiomesOPlenty-1.12.2-7.0.1.2302-universal.jar      | None                                     |
	| UCHIJAAAA | craftstudioapi      | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar              | None                                     |
	| UCHIJAAAA | quark               | r1.4-122                 | Quark-r1.4-122.jar                                 | None                                     |
	| UCHIJAAAA | animania            | 1.4.5                    | animania-1.12.2-1.4.5.jar                          | None                                     |
	| UCHIJAAAA | antiqueatlas        | 4.4.4                    | antiqueatlas-1.12-4.4.4.jar                        | None                                     |
	| UCHIJAAAA | antiqueatlasoverlay | 1.2                      | antiqueatlas-1.12-4.4.4.jar                        | None                                     |
	| UCHIJAAAA | anvils              | 1.4.0.0                  | AnvilEnchantments-1.12.2-1.4.0.0.jar               | None                                     |
	| UCHIJAAAA | crafttweaker        | 4.1.2                    | CraftTweaker2-1.12-4.1.2.jar                       | None                                     |
	| UCHIJAAAA | mtlib               | @VERSION@                | MTLib-3.0.1.jar                                    | None                                     |
	| UCHIJAAAA | modtweaker          | 4.0.6                    | modtweaker-4.0.6.jar                               | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.138                | jei_1.12.2-4.8.5.138.jar                           | None                                     |
	| UCHIJAAAA | appleskin           | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| UCHIJAAAA | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                           | None                                     |
	| UCHIJAAAA | thedragonlib        | 1.12.2-5.2.0             | thedragonlib-1.12.2-5.2.0.jar                      | None                                     |
	| UCHIJAAAA | armorplus           | 1.12.2-11.10.1.35-beta   | armorplus-1.12.2-11.10.1.35-beta.jar               | None                                     |
	| UCHIJAAAA | autoreglib          | 1.3-15                   | AutoRegLib-1.3-15.jar                              | None                                     |
	| UCHIJAAAA | backpacks16840      | 3.4.3                    | backpacks 1.12.2 - 3.4.3.jar                       | None                                     |
	| UCHIJAAAA | base                | 3.6.0                    | base-1.12.2-3.6.0.jar                              | None                                     |
	| UCHIJAAAA | baubles             | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UCHIJAAAA | betterfoliage       | 2.1.10                   | BetterFoliage-MC1.12-2.1.10.jar                    | None                                     |
	| UCHIJAAAA | betterquesting      | 3.5.238                  | BetterQuesting-3.5.238.jar                         | None                                     |
	| UCHIJAAAA | bqt                 | 0.9C                     | BetterQuestingTriggerer-0.9C.jar                   | None                                     |
	| UCHIJAAAA | bloodmoon           | 1.5.2                    | Bloodmoon-MC1.12.2-1.5.2.jar                       | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | ceramics            | 1.12-1.3.3b              | Ceramics-1.12-1.3.3b.jar                           | None                                     |
	| UCHIJAAAA | clienttweaks        | 3.1.2                    | ClientTweaks_1.12-3.1.2.jar                        | None                                     |
	| UCHIJAAAA | clumps              | 2.0.0                    | Clumps-3.0.0.jar                                   | None                                     |
	| UCHIJAAAA | extendedrenderer    | v1.0                     | coroutil-1.12.1-1.1.24.jar                         | None                                     |
	| UCHIJAAAA | coroutil            | 1.12.1-1.1.24            | coroutil-1.12.1-1.1.24.jar                         | None                                     |
	| UCHIJAAAA | configmod           | v1.0                     | coroutil-1.12.1-1.1.24.jar                         | None                                     |
	| UCHIJAAAA | ctgui               | 1.0.0                    | CraftTweaker2-1.12-4.1.2.jar                       | None                                     |
	| UCHIJAAAA | crafttweakerjei     | 2.0.0                    | CraftTweaker2-1.12-4.1.2.jar                       | None                                     |
	| UCHIJAAAA | customnpcs          | 1.12                     | CustomNPCs_1.12.2(20jan18).jar                     | None                                     |
	| UCHIJAAAA | dailies             | 1.12.2-6                 | dailies-1.12.2-6.jar                               | None                                     |
	| UCHIJAAAA | gottschcore         | 1.2.0                    | GottschCore-mc1.12.2-f14.23.1.2555-v1.2.0.jar      | None                                     |
	| UCHIJAAAA | dungeons2           | 1.3.2                    | Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.2.jar        | None                                     |
	| UCHIJAAAA | dungeontactics      | DT-0.14.2                | DungeonTactics-1.12.2-0.14.2.jar                   | None                                     |
	| UCHIJAAAA | dsurround           | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets             | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar             | None                                     |
	| UCHIJAAAA | extraalchemy        | 0.3.7.1-release          | extraalchemy-0.3.7.1-release.jar                   | None                                     |
	| UCHIJAAAA | natura              | 1.12.2-4.3.2.42          | natura-1.12.2-4.3.2.42.jar                         | None                                     |
	| UCHIJAAAA | forestry            | 5.8.0.242                | forestry_1.12.2-5.8.0.242.jar                      | None                                     |
	| UCHIJAAAA | gravestone          | 1.10.1                   | gravestone-1.10.1.jar                              | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | levelup2            | ${version}               | Level Up! 2-1.1.15-1.12.jar                        | None                                     |
	| UCHIJAAAA | lootbags            | 2.5.3b                   | LootBags-1.12.2-2.5.3b.jar                         | None                                     |
	| UCHIJAAAA | loottweaker         | 0.0.6.5                  | LootTweaker-1.12-0.0.6.5.jar                       | None                                     |
	| UCHIJAAAA | mapgadgets          | @VERSION@                | Mapmaker's+Gadgets-1.1.jar                         | None                                     |
	| UCHIJAAAA | mousetweaks         | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                       | None                                     |
	| UCHIJAAAA | openglider          | @VERSION@                | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
	| UCHIJAAAA | quickleafdecay      | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                  | None                                     |
	| UCHIJAAAA | reccomplex          | 1.4.7                    | RecurrentComplex-1.4.7.jar                         | None                                     |
	| UCHIJAAAA | roguelike           | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                 | None                                     |
	| UCHIJAAAA | roots               | 0.104                    | roots-2-0.104.jar                                  | None                                     |
	| UCHIJAAAA | silentlib           | 2.2.16                   | SilentLib-1.12-2.2.16-97.jar                       | None                                     |
	| UCHIJAAAA | scalinghealth       | 1.3.9                    | ScalingHealth-1.12-1.3.9-89.jar                    | None                                     |
	| UCHIJAAAA | spartanweaponry     | beta 1.1.2               | SpartanWeaponry-1.12.2-beta-1.1.2.jar              | None                                     |
	| UCHIJAAAA | bq_standard         | 3.4.136                  | StandardExpansion-3.4.136.jar                      | None                                     |
	| UCHIJAAAA | thebetweenlands     | 3.2.1-alpha-snapshot     | TheBetweenlands-3.2.1-alpha-snapshot-universal.jar | None                                     |
	| UCHIJAAAA | corerm              | 1.2h                     | TheCampingMod_2.3g.jar                             | None                                     |
	| UCHIJAAAA | camping             | 2.3g                     | TheCampingMod_2.3g.jar                             | None                                     |
	| UCHIJAAAA | toolbelt            | 1.7.1                    | ToolBelt-1.12.0-1.7.1.jar                          | None                                     |
	| UCHIJAAAA | toroquest           | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                           | None                                     |
	| UCHIJAAAA | xat                 | 0.14                     | Trinkets-and-Baubles-1.12.2-0.14.jar               | None                                     |
	| UCHIJAAAA | twilightforest      | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar        | None                                     |
	| UCHIJAAAA | weather2            | 1.12.1-2.5.7             | weather2-1.12.1-2.5.7.jar                          | None                                     |
	| UCHIJAAAA | wolfarmor           | 1.12.2-2.1.0-RELEASE     | wolfarmor-1.12.2-2.1.0.24-RELEASE.jar              | None                                     |

	Loaded coremods (and transformers): 
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.2.1-alpha-snapshot-universal.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.2.jar)
  lumien.bloodmoon.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
SHLoadingPlugin (ScalingHealth-1.12-1.3.9-89.jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
LoadingPlugin (Quark-r1.4-122.jar)
  vazkii.quark.base.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
BCModPlugin (backpacks 1.12.2 - 3.4.3.jar)
  brad16840.core.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['mando222'/1214, l='test2', x=471.30, y=66.00, z=454.02]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: KUDA-Shaders v6.5.56.zip
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[20:52:27] [main/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\mando222\Documents\Curse\Minecraft\Instances\Nomads\crash-reports\crash-2018-02-05_20.52.26-server.txt
[20:52:27] [main/INFO]: Waiting for the server to terminate/save.
[20:52:27] [Server thread/INFO]: mando222 lost connection: Server closed
[20:52:27] [Server thread/INFO]: mando222 left the game
[20:52:27] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:52:27] [Server thread/INFO]: Saving worlds
[20:52:27] [Server thread/INFO]: Saving chunks for level 'test2'/overworld
[20:52:27] [Server thread/INFO]: Saving chunks for level 'test2'/the_nether
[20:52:27] [Server thread/INFO]: Saving chunks for level 'test2'/the_end
[20:52:27] [Server thread/INFO]: Saving chunks for level 'test2'/Betweenlands
[20:52:27] [Server thread/INFO]: Saving chunks for level 'test2'/twilight_forest
[20:52:28] [Server thread/INFO]: Unloading dimension 0
[20:52:28] [Server thread/INFO]: Unloading dimension -1
[20:52:28] [Server thread/INFO]: Unloading dimension 1
[20:52:28] [Server thread/INFO]: Unloading dimension 20
[20:52:28] [Server thread/INFO]: Unloading dimension 7
[20:52:29] [Server thread/INFO]: Applying holder lookups
[20:52:29] [Server thread/INFO]: Holder lookups applied
[20:52:29] [Server thread/INFO]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[20:52:29] [main/INFO]: Server terminated.```

**Comment by mando222** [comment]
This seems to be the issue in question 
http://www.minecraftforge.net/forum/topic/62860-crash-biomesoplenty-blockbopgrassbopgrasstype/

**Comment by mando222** [comment]
Might be duplicate block ids between the two packs.  May be able to edit it to fix.

**Comment by mando222** [comment]
The error that caused the other issues.

`[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:760) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=camping:hemp, properties=[age]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209) ~[awu$a.class:?]
	at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:139) ~[BlockBOPGrass.class:?]
	at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:75) ~[Hemp.class:?]
	at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56) ~[Hemp.class:?]
	at net.minecraft.block.Block.func_180645_a(Block.java:508) ~[aow.class:?]
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225) ~[oo.class:?]
	at WorldServerOF.func_72835_b(WorldServerOF.java:37) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) ~[MinecraftServer.class:?]
	... 4 more
[20:52:27] [Server thread/ERROR]: This crash report has been saved to: C:\Users\mando222\Documents\Curse\Minecraft\Instances\Nomads\crash-reports\crash-2018-02-05_20.52.26-server.txt
`

**Comment by mando222** [comment]
Verified that it seems to be the BOP blockBOPGrass and Camping hemp conflicting.

**Comment by mando222** [comment]
this is the issue on bioms page https://github.com/Glitchfiend/BiomesOPlenty/issues/1174

**Comment by mando222** [comment]
the fix of the issue https://github.com/Rikmuld/MC-Camping/issues/102

**Comment by mando222** [comment]
Will be fixed in next version of camping mod.

**Comment by ilKestrelHawkli** [comment]
Removed the Camping hemp from generating.
